apiVersion: apps/v1
kind: Deployment 
metadata:
  name: boardgame-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boardgame
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      containers:
        - name: boardgame
          image: diogobarros03/boardshack:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
